### ISSUE TITLE
About run evaluate.py file.

### ISSUE THREAD

**Issue by 17011813** [kaize0409/Meta-GDN_AnomalyDetection#3]
Hello! I'm so glad to find your paper and code. Your paper is really interesting and wonderful.

I tried to run your code **python evaluate.py**, but I've got an error message like

FileNotFoundError: [Errno 2] No such file or directory: 'results/auc_12_01_15_38_yelp.txt'

How can I get 'results/auc_"%m_%d_%H_%M"_yelp.txt' file to run your code??

Also, I think it'd be really helpful if you could tell me in more detail explanations about how to run your code.

Thank you!!! Have a great day :)

**Comment by imethanlee** [comment]
^I have the same question about the data file

**Comment by BlueWhaleZhou** [comment]
Hi, I have done some updates to the code as well as the graph files. I think the code should work now. Please let me know if you have further questions. Thanks!

**Comment by 17011813** [comment]
Thanks for your kind answers and updates!
But I tried to run your code python evaluate.py, again but I've got an error message like
Namespace(epoch=20, meta_lr=0.001, n_way=1, task_num=5, update_lr=0.01, update_step=5, update_step_test=10)
Traceback (most recent call last):
  File "evaluate.py", line 130, in <module>
    main()
  File "evaluate.py", line 39, in main
    taskData.loadNProcess()
  File "C:\Users\yoona\Desktop\Meta-GDN_AnomalyDetection-main\process_task.py", line 49, in loadNProcess
    f_l = random.sample(l, self.nb_task)
  File "C:\Users\yoona\anaconda3\envs\pro\lib\random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative


How can I handle this error?

Thank you again!!

**Comment by BlueWhaleZhou** [comment]
Hi,

On my end it is running OK.

This error is due to a smaller number of graph files than the defined
"task_num" so that the sampling space is not enough.

Have you also downloaded all .mat files into the "graphs/pubmed" directory?
If you are using a smaller number of tasks (right now it is 5), make sure
to change this parameter as well.

Thank you.

**Comment by 17011813** [comment]
Hello, Merry Christmas!!
I have one more question.

I ran your code with PubMed dataset. And I wanna try your code with **Reddit and Yelp** dataset. But with your repository I can't find **Reddit and Yelp** folder in graphs.

Can you upload **Reddit and Yelp** folders in graphs folder?

Thank you! Be safe!
