### ISSUE TITLE
Training for non-meta-learning GNN-based baselines 

### ISSUE THREAD

**Issue by imethanlee** [kaize0409/Meta-GDN_AnomalyDetection#4]
Hi,

I would like to ask for some details on the tranining process of GNN-based baselines (e.g., GDN, Semi-GNN, DOMINANT). Which part of the dataset is these models trained on? The question comes to me because the paper mentions '4 auxilary networks and 1 target network ' for Meta-GDN. Do you use only the 1 target network to train these GNN-based baselines, or the 4 auxilary networks are also included?

Thanks in advance :)

**Comment by imethanlee** [comment]
May I also know how many tasks you have constructed for each of the three datasets?

**Comment by BlueWhaleZhou** [comment]
1. For supervised baseline methods, they are evaluated on the target network with the same number of labeled nodes (i.e., including the labeled nodes from the auxiliary networks for Meta-GDN) for a fair comparison.
2. We use 5 networks, including 4 auxiliary networks and 1 target one, as described in the paper.

**Comment by imethanlee** [comment]
Thanks for the answer!
